// Do not modify this file. It's generated by Framework.Cli generate command.

namespace DatabaseIntegrate.dbo
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Database.dbo;

    public static class FrameworkConfigGridIntegrateAppCli
    {
        public static List<FrameworkConfigGridIntegrate> RowList
        {
            get
            {
                var result = new List<FrameworkConfigGridIntegrate>
                {
                };
                return result;
            }
        }
    }

    public static class FrameworkConfigFieldIntegrateAppCli
    {
        public static List<FrameworkConfigFieldIntegrate> RowList
        {
            get
            {
                var result = new List<FrameworkConfigFieldIntegrate>
                {
                };
                return result;
            }
        }
    }
}

namespace DatabaseIntegrate.Doc
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Database.Doc;

    public static class NavigateIntegrateAppCli
    {
        public static List<NavigateIntegrate> RowList
        {
            get
            {
                var result = new List<NavigateIntegrate>
                {
                    new NavigateIntegrate { Id = 0, ParentId = 0, Name = "Admin", TextHtml = "<i class=\"fas fa-shield-alt\"></i> Admin", IsDivider = false, IsNavbarEnd = false, NavigatePath = null, PageTypeName = null, Sort = 21, IdName = "Admin", ParentIdName = null },
                    new NavigateIntegrate { Id = 0, ParentId = 0, Name = "AdminLoginUserRole", TextHtml = "<i class=\"fas fa-user\"></i> User", IsDivider = false, IsNavbarEnd = false, NavigatePath = "/admin-user-role/", PageTypeName = "PageAdminLoginUserRole", Sort = 5, IdName = "AdminLoginUserRole", ParentIdName = "Home" },
                    new NavigateIntegrate { Id = 0, ParentId = 0, Name = "Home", TextHtml = "<i class=\"fas fa-home\"></i> Home", IsDivider = false, IsNavbarEnd = false, NavigatePath = "/", PageTypeName = "PageHome", Sort = 1, IdName = "Home", ParentIdName = null },
                    new NavigateIntegrate { Id = 0, ParentId = 0, Name = "LoginSignIn", TextHtml = "<i class=\"fas fa-sign-in-alt\"></i> Sign in", IsDivider = false, IsNavbarEnd = true, NavigatePath = "/signin/", PageTypeName = "PageLoginSignIn", Sort = 2, IdName = "LoginSignIn", ParentIdName = null },
                    new NavigateIntegrate { Id = 0, ParentId = 0, Name = "LoginSignOut", TextHtml = "<i class=\"fas fa-sign-out-alt\"></i> Sign out", IsDivider = false, IsNavbarEnd = true, NavigatePath = "/signout/", PageTypeName = "PageLoginSignOut", Sort = 3, IdName = "LoginSignOut", ParentIdName = null },
                    new NavigateIntegrate { Id = 0, ParentId = 0, Name = "LoginSignUp", TextHtml = "<i class=\"fas fa-user-plus\"></i> Sign up", IsDivider = false, IsNavbarEnd = true, NavigatePath = "/signup/", PageTypeName = "PageLoginSignUp", Sort = 1, IdName = "LoginSignUp", ParentIdName = null },
                };
                return result;
            }
        }
    }

    public static class LoginUserIntegrateAppCli
    {
        public static List<LoginUserIntegrate> RowList
        {
            get
            {
                var result = new List<LoginUserIntegrate>
                {
                    new LoginUserIntegrate { Id = 0, Name = "Admin", Password = null, IsIntegrate = true, IsDelete = false, IdName = "Admin" },
                    new LoginUserIntegrate { Id = 0, Name = "Developer", Password = null, IsIntegrate = true, IsDelete = false, IdName = "Developer" },
                    new LoginUserIntegrate { Id = 0, Name = "Guest", Password = null, IsIntegrate = true, IsDelete = false, IdName = "Guest" },
                };
                return result;
            }
        }
    }

    public static class LoginUserRoleIntegrateAppCli
    {
        public static List<LoginUserRoleIntegrate> RowList
        {
            get
            {
                var result = new List<LoginUserRoleIntegrate>
                {
                    new LoginUserRoleIntegrate { Id = 0, LoginUserId = 0, LoginRoleId = 0, IsActive = null, LoginUserIsIntegrate = true, LoginUserIdName = "Admin", LoginRoleIdName = "Admin" },
                    new LoginUserRoleIntegrate { Id = 0, LoginUserId = 0, LoginRoleId = 0, IsActive = null, LoginUserIsIntegrate = true, LoginUserIdName = "Developer", LoginRoleIdName = "Developer" },
                    new LoginUserRoleIntegrate { Id = 0, LoginUserId = 0, LoginRoleId = 0, IsActive = true, LoginUserIsIntegrate = true, LoginUserIdName = "Guest", LoginRoleIdName = "Guest" },
                };
                return result;
            }
        }
    }

    public static class NavigateRoleIntegrateAppCli
    {
        public static List<NavigateRoleIntegrate> RowList
        {
            get
            {
                var result = new List<NavigateRoleIntegrate>
                {
                    new NavigateRoleIntegrate { Id = 0, NavigateId = 0, LoginRoleId = 0, IsActive = true, NavigateIdName = "Home", LoginRoleIdName = "Guest" },
                    new NavigateRoleIntegrate { Id = 0, NavigateId = 0, LoginRoleId = 0, IsActive = true, NavigateIdName = "LoginSignIn", LoginRoleIdName = "Guest" },
                };
                return result;
            }
        }
    }

    public static class StorageFileIntegrateAppCli
    {
        public static List<StorageFileIntegrate> RowList
        {
            get
            {
                var result = new List<StorageFileIntegrate>
                {
                };
                return result;
            }
        }
    }
}
