namespace Framework.Cli.Generate
{
    using System.Text;

    public class GenerateCSharpBuiltIn
    {
        public GenerateCSharpBuiltIn(MetaCSharp metaCSharp)
        {
            this.MetaCSharp = metaCSharp;
        }

        public readonly MetaCSharp MetaCSharp;

        /// <summary>
        /// Generate CSharp code.
        /// </summary>
        /// <param name="isApplication">If false, generate code for cli. If true, generate code for Application</param>
        public void Run(out string cSharp, bool isApplication)
        {
            StringBuilder result = new StringBuilder();
            result.AppendLine("// Do not modify this file. It's generated by Framework.Cli.");
            result.AppendLine();
            cSharp = result.ToString();
        }
    }
}
