// Do not modify this file. It's generated by Framework.Cli.

namespace DatabaseIntegrate.dbo
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Database.dbo;

    public static class FrameworkConfigGridIntegrateFrameworkCli
    {
        public static List<FrameworkConfigGridIntegrate> RowList
        {
            get
            {
                var result = new List<FrameworkConfigGridIntegrate>
                {
                    new FrameworkConfigGridIntegrate {Id = 1, IdName = "dbo.FrameworkConfigFieldDisplay; ", TableId = 2, TableIdName = "dbo.FrameworkConfigFieldDisplay", TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, RowCountMax = null, IsAllowInsert = null, IsExist = true },
                    new FrameworkConfigGridIntegrate {Id = 2, IdName = "dbo.FrameworkConfigGridDisplay; ", TableId = 5, TableIdName = "dbo.FrameworkConfigGridDisplay", TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, RowCountMax = null, IsAllowInsert = null, IsExist = true },
                };
                return result;
            }
        }
    }

    public static class FrameworkConfigFieldIntegrateFrameworkCli
    {
        public static List<FrameworkConfigFieldIntegrate> RowList
        {
            get
            {
                var result = new List<FrameworkConfigFieldIntegrate>
                {
                    new FrameworkConfigFieldIntegrate {Id = 1, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 12, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldDescription", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldDescription", Text = "Description", Description = "Description", IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 2, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 15, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldInstanceName", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldInstanceName", Text = "Instance Name", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 3, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 16, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldIsReadOnly", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldIsReadOnly", Text = "Readonly", Description = "Readonly", IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 4, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 17, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldIsVisible", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldIsVisible", Text = "Visible", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 5, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 18, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldSort", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldSort", Text = "Sort", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 6, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 19, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldText", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldText", Text = "Text", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 7, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 20, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigGridConfigName", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigGridConfigName", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 8, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 22, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigGridIsExist", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigGridIsExist", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 9, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 24, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigGridTableIdName", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigGridTableIdName", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 10, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 25, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigGridTableNameCSharp", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigGridTableNameCSharp", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 11, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 26, FieldIdName = "dbo.FrameworkConfigFieldDisplay; FieldFieldNameCSharp", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "FieldFieldNameCSharp", Text = "Field Name", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 12, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 27, FieldIdName = "dbo.FrameworkConfigFieldDisplay; FieldFieldNameSql", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "FieldFieldNameSql", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 13, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 30, FieldIdName = "dbo.FrameworkConfigFieldDisplay; FieldIsExist", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "FieldIsExist", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 14, ConfigGridId = 2, ConfigGridIdName = "dbo.FrameworkConfigGridDisplay; ", FieldId = 55, FieldIdName = "dbo.FrameworkConfigGridDisplay; IsAllowInsert", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, FieldNameCSharp = "IsAllowInsert", Text = "Allow Insert", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 15, ConfigGridId = 2, ConfigGridIdName = "dbo.FrameworkConfigGridDisplay; ", FieldId = 56, FieldIdName = "dbo.FrameworkConfigGridDisplay; IsExist", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, FieldNameCSharp = "IsExist", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 16, ConfigGridId = 2, ConfigGridIdName = "dbo.FrameworkConfigGridDisplay; ", FieldId = 57, FieldIdName = "dbo.FrameworkConfigGridDisplay; RowCountMax", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, FieldNameCSharp = "RowCountMax", Text = "Row Count", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 17, ConfigGridId = 2, ConfigGridIdName = "dbo.FrameworkConfigGridDisplay; ", FieldId = 59, FieldIdName = "dbo.FrameworkConfigGridDisplay; TableNameCSharp", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, FieldNameCSharp = "TableNameCSharp", Text = "Table Name", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 18, ConfigGridId = 2, ConfigGridIdName = "dbo.FrameworkConfigGridDisplay; ", FieldId = 60, FieldIdName = "dbo.FrameworkConfigGridDisplay; TableNameSql", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, FieldNameCSharp = "TableNameSql", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                };
                return result;
            }
        }
    }
}
