// Do not modify this file. It's generated by Framework.Cli.

namespace DatabaseIntegrate.dbo
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Database.dbo;

    public static class FrameworkConfigGridIntegrateFrameworkCli
    {
        public static List<FrameworkConfigGridIntegrate> RowList
        {
            get
            {
                var result = new List<FrameworkConfigGridIntegrate>
                {
                    new FrameworkConfigGridIntegrate {Id = 0, IdName = "dbo.FrameworkConfigFieldDisplay; ", TableId = 0, TableIdName = "dbo.FrameworkConfigFieldDisplay", TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, RowCountMax = null, IsAllowInsert = null, IsExist = true },
                    new FrameworkConfigGridIntegrate {Id = 0, IdName = "dbo.FrameworkConfigGridDisplay; ", TableId = 0, TableIdName = "dbo.FrameworkConfigGridDisplay", TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, RowCountMax = null, IsAllowInsert = null, IsExist = true },
                };
                return result;
            }
        }
    }

    public static class FrameworkConfigFieldIntegrateFrameworkCli
    {
        public static List<FrameworkConfigFieldIntegrate> RowList
        {
            get
            {
                var result = new List<FrameworkConfigFieldIntegrate>
                {
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldDescription", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldDescription", Text = "Description", Description = "Description", IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldInstanceName", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldInstanceName", Text = "Instance Name", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldIsReadOnly", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldIsReadOnly", Text = "Readonly", Description = "Readonly", IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldIsVisible", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldIsVisible", Text = "Visible", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldSort", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldSort", Text = "Sort", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldText", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldText", Text = "Text", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigGridConfigName", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigGridConfigName", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigGridIsExist", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigGridIsExist", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigGridTableIdName", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigGridTableIdName", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigGridTableNameCSharp", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigGridTableNameCSharp", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigFieldDisplay; FieldFieldNameCSharp", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "FieldFieldNameCSharp", Text = "Field Name", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigFieldDisplay; FieldFieldNameSql", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "FieldFieldNameSql", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigFieldDisplay; FieldFieldSort", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "FieldFieldSort", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigFieldDisplay; FieldIsExist", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "FieldIsExist", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigGridDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigGridDisplay; IsAllowInsert", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, FieldNameCSharp = "IsAllowInsert", Text = "Allow Insert", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigGridDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigGridDisplay; IsExist", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, FieldNameCSharp = "IsExist", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigGridDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigGridDisplay; RowCountMax", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, FieldNameCSharp = "RowCountMax", Text = "Row Count", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigGridDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigGridDisplay; TableNameCSharp", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, FieldNameCSharp = "TableNameCSharp", Text = "Table Name", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldIntegrate {Id = 0, ConfigGridId = 0, ConfigGridIdName = "dbo.FrameworkConfigGridDisplay; ", FieldId = 0, FieldIdName = "dbo.FrameworkConfigGridDisplay; TableNameSql", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, FieldNameCSharp = "TableNameSql", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                };
                return result;
            }
        }
    }
}
