// Do not modify this file. It's generated by Framework.Cli.

namespace DatabaseBuiltIn.dbo
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Database.dbo;

    public static class FrameworkConfigGridBuiltInFrameworkCli
    {
        public static List<FrameworkConfigGridBuiltIn> RowList
        {
            get
            {
                var result = new List<FrameworkConfigGridBuiltIn>
                {
                    new FrameworkConfigGridBuiltIn {Id = 1, IdName = "dbo.FrameworkConfigFieldDisplay; ", TableId = 3, TableIdName = "dbo.FrameworkConfigFieldDisplay", TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, RowCountMax = null, IsAllowInsert = null, IsExist = true },
                    new FrameworkConfigGridBuiltIn {Id = 2, IdName = "dbo.FrameworkConfigGridDisplay; ", TableId = 6, TableIdName = "dbo.FrameworkConfigGridDisplay", TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, RowCountMax = null, IsAllowInsert = null, IsExist = true },
                };
                return result;
            }
        }
    }

    public static class FrameworkConfigFieldBuiltInFrameworkCli
    {
        public static List<FrameworkConfigFieldBuiltIn> RowList
        {
            get
            {
                var result = new List<FrameworkConfigFieldBuiltIn>
                {
                    new FrameworkConfigFieldBuiltIn {Id = 1, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 27, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldDescription", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldDescription", Text = "Description", Description = "Description", IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 2, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 30, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldInstanceName", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldInstanceName", Text = "Instance Name", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 3, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 31, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldIsReadOnly", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldIsReadOnly", Text = "Readonly", Description = "Readonly", IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 4, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 32, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldIsVisible", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldIsVisible", Text = "Visible", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 5, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 33, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldSort", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldSort", Text = "Sort", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 6, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 34, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigFieldText", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigFieldText", Text = "Text", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 7, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 35, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigGridConfigName", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigGridConfigName", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 8, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 37, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigGridIsExist", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigGridIsExist", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 9, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 39, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigGridTableIdName", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigGridTableIdName", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 10, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 40, FieldIdName = "dbo.FrameworkConfigFieldDisplay; ConfigGridTableNameCSharp", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "ConfigGridTableNameCSharp", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 11, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 41, FieldIdName = "dbo.FrameworkConfigFieldDisplay; FieldFieldNameCSharp", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "FieldFieldNameCSharp", Text = "Field Name", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 12, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 42, FieldIdName = "dbo.FrameworkConfigFieldDisplay; FieldFieldNameSql", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "FieldFieldNameSql", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 13, ConfigGridId = 1, ConfigGridIdName = "dbo.FrameworkConfigFieldDisplay; ", FieldId = 44, FieldIdName = "dbo.FrameworkConfigFieldDisplay; FieldIsExist", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, FieldNameCSharp = "FieldIsExist", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 14, ConfigGridId = 2, ConfigGridIdName = "dbo.FrameworkConfigGridDisplay; ", FieldId = 63, FieldIdName = "dbo.FrameworkConfigGridDisplay; IsAllowInsert", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, FieldNameCSharp = "IsAllowInsert", Text = "Allow Insert", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 15, ConfigGridId = 2, ConfigGridIdName = "dbo.FrameworkConfigGridDisplay; ", FieldId = 64, FieldIdName = "dbo.FrameworkConfigGridDisplay; IsExist", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, FieldNameCSharp = "IsExist", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 16, ConfigGridId = 2, ConfigGridIdName = "dbo.FrameworkConfigGridDisplay; ", FieldId = 65, FieldIdName = "dbo.FrameworkConfigGridDisplay; RowCountMax", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, FieldNameCSharp = "RowCountMax", Text = "Row Count", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 17, ConfigGridId = 2, ConfigGridIdName = "dbo.FrameworkConfigGridDisplay; ", FieldId = 67, FieldIdName = "dbo.FrameworkConfigGridDisplay; TableNameCSharp", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, FieldNameCSharp = "TableNameCSharp", Text = "Table Name", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true },
                    new FrameworkConfigFieldBuiltIn {Id = 18, ConfigGridId = 2, ConfigGridIdName = "dbo.FrameworkConfigGridDisplay; ", FieldId = 68, FieldIdName = "dbo.FrameworkConfigGridDisplay; TableNameSql", InstanceName = null, TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, FieldNameCSharp = "TableNameSql", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true },
                };
                return result;
            }
        }
    }
}
