// Do not modify this file. It's generated by Framework.Cli.

namespace DatabaseBuiltIn.dbo
{
    using System.Collections.Generic;
    using Database.dbo;

    public static class FrameworkConfigFieldBuiltInMemory
    {
        public static List<FrameworkConfigFieldBuiltIn> List
        {
            get
            {
                var result = new List<FrameworkConfigFieldBuiltIn>();
                return result;
            }
        }
    }

    public static class FrameworkConfigGridBuiltInMemory
    {
        public static List<FrameworkConfigGridBuiltIn> List
        {
            get
            {
                var result = new List<FrameworkConfigGridBuiltIn>();
                return result;
            }
        }
    }

    public static class FrameworkFieldBuiltInMemory
    {
        public static List<FrameworkFieldBuiltIn> List
        {
            get
            {
                var result = new List<FrameworkFieldBuiltIn>();
                return result;
            }
        }
    }

    public static class FrameworkTableBuiltInMemory
    {
        public static List<FrameworkTableBuiltIn> List
        {
            get
            {
                var result = new List<FrameworkTableBuiltIn>();
                return result;
            }
        }
    }
}
