// Do not modify this file. It's generated by Framework.Cli generate command.

namespace DatabaseIntegrate.dbo
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Threading.Tasks;
    using Framework.DataAccessLayer;
    using Database.dbo;

    public static class FrameworkConfigGridIntegrateFramework
    {
        public enum IdEnum { [IdEnum(null)]None = 0, [IdEnum("dbo.FrameworkConfigFieldDisplay; ")]dboFrameworkConfigFieldDisplay = -1, [IdEnum("dbo.FrameworkConfigFieldDisplay; Developer")]dboFrameworkConfigFieldDisplayDeveloper = -2, [IdEnum("dbo.FrameworkConfigGridDisplay; ")]dboFrameworkConfigGridDisplay = -3, [IdEnum("dbo.FrameworkConfigGridDisplay; Developer")]dboFrameworkConfigGridDisplayDeveloper = -4 }

        public static FrameworkConfigGridIntegrate Row(this IdEnum value)
        {
            return RowList.Where(item => item.IdName == IdEnumAttribute.IdNameFromEnum(value)).SingleOrDefault();
        }

        public static IdEnum IdName(string value)
        {
            return IdEnumAttribute.IdNameToEnum<IdEnum>(value);
        }

        public static string IdName(this IdEnum value)
        {
            return IdEnumAttribute.IdNameFromEnum(value);
        }

        public static async Task<int> Id(this IdEnum value)
        {
            return (await Data.Query<FrameworkConfigGridIntegrate>().Where(item => item.IdName == IdEnumAttribute.IdNameFromEnum(value)).QueryExecuteAsync()).Single().Id;
        }

        public static List<FrameworkConfigGridIntegrate> RowList
        {
            get
            {
                var result = new List<FrameworkConfigGridIntegrate>
                {
                    new FrameworkConfigGridIntegrate { Id = 0, IdName = "dbo.FrameworkConfigFieldDisplay; ", TableId = 0, TableIdName = "dbo.FrameworkConfigFieldDisplay", TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = null, RowCountMax = null, IsAllowInsert = false, IsShowHeader = null, IsShowPagination = null, IsDelete = false },
                    new FrameworkConfigGridIntegrate { Id = 0, IdName = "dbo.FrameworkConfigFieldDisplay; Developer", TableId = 0, TableIdName = "dbo.FrameworkConfigFieldDisplay", TableNameCSharp = "dbo.FrameworkConfigFieldDisplay", ConfigName = "Developer", RowCountMax = null, IsAllowInsert = false, IsShowHeader = null, IsShowPagination = null, IsDelete = false },
                    new FrameworkConfigGridIntegrate { Id = 0, IdName = "dbo.FrameworkConfigGridDisplay; ", TableId = 0, TableIdName = "dbo.FrameworkConfigGridDisplay", TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = null, RowCountMax = null, IsAllowInsert = false, IsShowHeader = null, IsShowPagination = null, IsDelete = false },
                    new FrameworkConfigGridIntegrate { Id = 0, IdName = "dbo.FrameworkConfigGridDisplay; Developer", TableId = 0, TableIdName = "dbo.FrameworkConfigGridDisplay", TableNameCSharp = "dbo.FrameworkConfigGridDisplay", ConfigName = "Developer", RowCountMax = null, IsAllowInsert = null, IsShowHeader = null, IsShowPagination = null, IsDelete = false },
                };
                return result;
            }
        }
    }
}
