// Do not modify this file. It's generated by BuildTool generate command.
//
namespace Database.dbo
{
    using Framework.DataAccessLayer;
    using System;

    [SqlTable("dbo", "FrameworkApplication")]
    public partial class FrameworkApplication : Row
    {
        [SqlColumn("Id", typeof(FrameworkApplication_Id), true)]
        public int Id { get; set; }

        [SqlColumn("Text", typeof(FrameworkApplication_Text))]
        public string Text { get; set; }

        [SqlColumn("Path", typeof(FrameworkApplication_Path))]
        public string Path { get; set; }

        [SqlColumn("ApplicationTypeId", typeof(FrameworkApplication_ApplicationTypeId))]
        public int ApplicationTypeId { get; set; }

        [SqlColumn("IsActive", typeof(FrameworkApplication_IsActive))]
        public bool? IsActive { get; set; }
    }

    public partial class FrameworkApplication_Id : Cell<FrameworkApplication> { }

    public partial class FrameworkApplication_Text : Cell<FrameworkApplication> { }

    public partial class FrameworkApplication_Path : Cell<FrameworkApplication> { }

    public partial class FrameworkApplication_ApplicationTypeId : Cell<FrameworkApplication> { }

    public partial class FrameworkApplication_IsActive : Cell<FrameworkApplication> { }

    [SqlTable("dbo", "FrameworkApplicationDisplay")]
    public partial class FrameworkApplicationDisplay : Row
    {
        [SqlColumn("Id", typeof(FrameworkApplicationDisplay_Id))]
        public int Id { get; set; }

        [SqlColumn("Text", typeof(FrameworkApplicationDisplay_Text))]
        public string Text { get; set; }

        [SqlColumn("Path", typeof(FrameworkApplicationDisplay_Path))]
        public string Path { get; set; }

        [SqlColumn("ApplicationTypeId", typeof(FrameworkApplicationDisplay_ApplicationTypeId))]
        public int ApplicationTypeId { get; set; }

        [SqlColumn("TypeName", typeof(FrameworkApplicationDisplay_TypeName))]
        public string TypeName { get; set; }

        [SqlColumn("IsExist", typeof(FrameworkApplicationDisplay_IsExist))]
        public bool? IsExist { get; set; }

        [SqlColumn("IsActive", typeof(FrameworkApplicationDisplay_IsActive))]
        public bool? IsActive { get; set; }
    }

    public partial class FrameworkApplicationDisplay_Id : Cell<FrameworkApplicationDisplay> { }

    public partial class FrameworkApplicationDisplay_Text : Cell<FrameworkApplicationDisplay> { }

    public partial class FrameworkApplicationDisplay_Path : Cell<FrameworkApplicationDisplay> { }

    public partial class FrameworkApplicationDisplay_ApplicationTypeId : Cell<FrameworkApplicationDisplay> { }

    public partial class FrameworkApplicationDisplay_TypeName : Cell<FrameworkApplicationDisplay> { }

    public partial class FrameworkApplicationDisplay_IsExist : Cell<FrameworkApplicationDisplay> { }

    public partial class FrameworkApplicationDisplay_IsActive : Cell<FrameworkApplicationDisplay> { }

    [SqlTable("dbo", "FrameworkApplicationType")]
    public partial class FrameworkApplicationType : Row
    {
        [SqlColumn("Id", typeof(FrameworkApplicationType_Id), true)]
        public int Id { get; set; }

        [SqlColumn("TypeName", typeof(FrameworkApplicationType_TypeName))]
        public string TypeName { get; set; }

        [SqlColumn("IsExist", typeof(FrameworkApplicationType_IsExist))]
        public bool IsExist { get; set; }
    }

    public partial class FrameworkApplicationType_Id : Cell<FrameworkApplicationType> { }

    public partial class FrameworkApplicationType_TypeName : Cell<FrameworkApplicationType> { }

    public partial class FrameworkApplicationType_IsExist : Cell<FrameworkApplicationType> { }

    [SqlTable("dbo", "FrameworkColumn")]
    public partial class FrameworkColumn : Row
    {
        [SqlColumn("Id", typeof(FrameworkColumn_Id), true)]
        public int Id { get; set; }

        [SqlColumn("TableId", typeof(FrameworkColumn_TableId))]
        public int TableId { get; set; }

        [SqlColumn("ColumnNameCSharp", typeof(FrameworkColumn_ColumnNameCSharp))]
        public string ColumnNameCSharp { get; set; }

        [SqlColumn("ColumnNameSql", typeof(FrameworkColumn_ColumnNameSql))]
        public string ColumnNameSql { get; set; }

        [SqlColumn("IsExist", typeof(FrameworkColumn_IsExist))]
        public bool IsExist { get; set; }
    }

    public partial class FrameworkColumn_Id : Cell<FrameworkColumn> { }

    public partial class FrameworkColumn_TableId : Cell<FrameworkColumn> { }

    public partial class FrameworkColumn_ColumnNameCSharp : Cell<FrameworkColumn> { }

    public partial class FrameworkColumn_ColumnNameSql : Cell<FrameworkColumn> { }

    public partial class FrameworkColumn_IsExist : Cell<FrameworkColumn> { }

    [SqlTable("dbo", "FrameworkComponent")]
    public partial class FrameworkComponent : Row
    {
        [SqlColumn("Id", typeof(FrameworkComponent_Id), true)]
        public int Id { get; set; }

        [SqlColumn("ComponentNameCSharp", typeof(FrameworkComponent_ComponentNameCSharp))]
        public string ComponentNameCSharp { get; set; }

        [SqlColumn("IsPage", typeof(FrameworkComponent_IsPage))]
        public bool IsPage { get; set; }

        [SqlColumn("IsExist", typeof(FrameworkComponent_IsExist))]
        public bool IsExist { get; set; }
    }

    public partial class FrameworkComponent_Id : Cell<FrameworkComponent> { }

    public partial class FrameworkComponent_ComponentNameCSharp : Cell<FrameworkComponent> { }

    public partial class FrameworkComponent_IsPage : Cell<FrameworkComponent> { }

    public partial class FrameworkComponent_IsExist : Cell<FrameworkComponent> { }

    [SqlTable("dbo", "FrameworkConfigColumn")]
    public partial class FrameworkConfigColumn : Row
    {
        [SqlColumn("Id", typeof(FrameworkConfigColumn_Id), true)]
        public int Id { get; set; }

        [SqlColumn("GridId", typeof(FrameworkConfigColumn_GridId))]
        public int GridId { get; set; }

        [SqlColumn("ColumnId", typeof(FrameworkConfigColumn_ColumnId))]
        public int ColumnId { get; set; }

        [SqlColumn("TextDefault", typeof(FrameworkConfigColumn_TextDefault))]
        public string TextDefault { get; set; }

        [SqlColumn("Text", typeof(FrameworkConfigColumn_Text))]
        public string Text { get; set; }

        [SqlColumn("DescriptionDefault", typeof(FrameworkConfigColumn_DescriptionDefault))]
        public string DescriptionDefault { get; set; }

        [SqlColumn("Description", typeof(FrameworkConfigColumn_Description))]
        public string Description { get; set; }

        [SqlColumn("IsVisibleDefault", typeof(FrameworkConfigColumn_IsVisibleDefault))]
        public bool? IsVisibleDefault { get; set; }

        [SqlColumn("IsVisible", typeof(FrameworkConfigColumn_IsVisible))]
        public bool? IsVisible { get; set; }

        [SqlColumn("IsReadOnlyDefault", typeof(FrameworkConfigColumn_IsReadOnlyDefault))]
        public bool? IsReadOnlyDefault { get; set; }

        [SqlColumn("IsReadOnly", typeof(FrameworkConfigColumn_IsReadOnly))]
        public bool? IsReadOnly { get; set; }

        [SqlColumn("SortDefault", typeof(FrameworkConfigColumn_SortDefault))]
        public double? SortDefault { get; set; }

        [SqlColumn("Sort", typeof(FrameworkConfigColumn_Sort))]
        public double? Sort { get; set; }

        [SqlColumn("WidthPercentDefault", typeof(FrameworkConfigColumn_WidthPercentDefault))]
        public double? WidthPercentDefault { get; set; }

        [SqlColumn("WidthPercent", typeof(FrameworkConfigColumn_WidthPercent))]
        public double? WidthPercent { get; set; }
    }

    public partial class FrameworkConfigColumn_Id : Cell<FrameworkConfigColumn> { }

    public partial class FrameworkConfigColumn_GridId : Cell<FrameworkConfigColumn> { }

    public partial class FrameworkConfigColumn_ColumnId : Cell<FrameworkConfigColumn> { }

    public partial class FrameworkConfigColumn_TextDefault : Cell<FrameworkConfigColumn> { }

    public partial class FrameworkConfigColumn_Text : Cell<FrameworkConfigColumn> { }

    public partial class FrameworkConfigColumn_DescriptionDefault : Cell<FrameworkConfigColumn> { }

    public partial class FrameworkConfigColumn_Description : Cell<FrameworkConfigColumn> { }

    public partial class FrameworkConfigColumn_IsVisibleDefault : Cell<FrameworkConfigColumn> { }

    public partial class FrameworkConfigColumn_IsVisible : Cell<FrameworkConfigColumn> { }

    public partial class FrameworkConfigColumn_IsReadOnlyDefault : Cell<FrameworkConfigColumn> { }

    public partial class FrameworkConfigColumn_IsReadOnly : Cell<FrameworkConfigColumn> { }

    public partial class FrameworkConfigColumn_SortDefault : Cell<FrameworkConfigColumn> { }

    public partial class FrameworkConfigColumn_Sort : Cell<FrameworkConfigColumn> { }

    public partial class FrameworkConfigColumn_WidthPercentDefault : Cell<FrameworkConfigColumn> { }

    public partial class FrameworkConfigColumn_WidthPercent : Cell<FrameworkConfigColumn> { }

    [SqlTable("dbo", "FrameworkConfigColumnDisplay")]
    public partial class FrameworkConfigColumnDisplay : Row
    {
        [SqlColumn("GridId", typeof(FrameworkConfigColumnDisplay_GridId))]
        public int GridId { get; set; }

        [SqlColumn("GridName", typeof(FrameworkConfigColumnDisplay_GridName))]
        public string GridName { get; set; }

        [SqlColumn("GridIsExist", typeof(FrameworkConfigColumnDisplay_GridIsExist))]
        public bool GridIsExist { get; set; }

        [SqlColumn("TableId", typeof(FrameworkConfigColumnDisplay_TableId))]
        public int? TableId { get; set; }

        [SqlColumn("TableNameCSharp", typeof(FrameworkConfigColumnDisplay_TableNameCSharp))]
        public string TableNameCSharp { get; set; }

        [SqlColumn("TableNameSql", typeof(FrameworkConfigColumnDisplay_TableNameSql))]
        public string TableNameSql { get; set; }

        [SqlColumn("TableIsExist", typeof(FrameworkConfigColumnDisplay_TableIsExist))]
        public bool? TableIsExist { get; set; }

        [SqlColumn("ColumnId", typeof(FrameworkConfigColumnDisplay_ColumnId))]
        public int? ColumnId { get; set; }

        [SqlColumn("ColumnNameCSharp", typeof(FrameworkConfigColumnDisplay_ColumnNameCSharp))]
        public string ColumnNameCSharp { get; set; }

        [SqlColumn("ColumnNameSql", typeof(FrameworkConfigColumnDisplay_ColumnNameSql))]
        public string ColumnNameSql { get; set; }

        [SqlColumn("ColumnIsExist", typeof(FrameworkConfigColumnDisplay_ColumnIsExist))]
        public bool? ColumnIsExist { get; set; }

        [SqlColumn("ConfigId", typeof(FrameworkConfigColumnDisplay_ConfigId))]
        public int? ConfigId { get; set; }

        [SqlColumn("TextDefault", typeof(FrameworkConfigColumnDisplay_TextDefault))]
        public string TextDefault { get; set; }

        [SqlColumn("Text", typeof(FrameworkConfigColumnDisplay_Text))]
        public string Text { get; set; }

        [SqlColumn("DescriptionDefault", typeof(FrameworkConfigColumnDisplay_DescriptionDefault))]
        public string DescriptionDefault { get; set; }

        [SqlColumn("Description", typeof(FrameworkConfigColumnDisplay_Description))]
        public string Description { get; set; }

        [SqlColumn("IsVisibleDefault", typeof(FrameworkConfigColumnDisplay_IsVisibleDefault))]
        public bool? IsVisibleDefault { get; set; }

        [SqlColumn("IsVisible", typeof(FrameworkConfigColumnDisplay_IsVisible))]
        public bool? IsVisible { get; set; }

        [SqlColumn("IsReadOnlyDefault", typeof(FrameworkConfigColumnDisplay_IsReadOnlyDefault))]
        public bool? IsReadOnlyDefault { get; set; }

        [SqlColumn("IsReadOnly", typeof(FrameworkConfigColumnDisplay_IsReadOnly))]
        public bool? IsReadOnly { get; set; }

        [SqlColumn("SortDefault", typeof(FrameworkConfigColumnDisplay_SortDefault))]
        public double? SortDefault { get; set; }

        [SqlColumn("Sort", typeof(FrameworkConfigColumnDisplay_Sort))]
        public double? Sort { get; set; }

        [SqlColumn("WidthPercentDefault", typeof(FrameworkConfigColumnDisplay_WidthPercentDefault))]
        public double? WidthPercentDefault { get; set; }

        [SqlColumn("WidthPercent", typeof(FrameworkConfigColumnDisplay_WidthPercent))]
        public double? WidthPercent { get; set; }
    }

    public partial class FrameworkConfigColumnDisplay_GridId : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_GridName : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_GridIsExist : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_TableId : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_TableNameCSharp : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_TableNameSql : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_TableIsExist : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_ColumnId : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_ColumnNameCSharp : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_ColumnNameSql : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_ColumnIsExist : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_ConfigId : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_TextDefault : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_Text : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_DescriptionDefault : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_Description : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_IsVisibleDefault : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_IsVisible : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_IsReadOnlyDefault : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_IsReadOnly : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_SortDefault : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_Sort : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_WidthPercentDefault : Cell<FrameworkConfigColumnDisplay> { }

    public partial class FrameworkConfigColumnDisplay_WidthPercent : Cell<FrameworkConfigColumnDisplay> { }

    [SqlTable("dbo", "FrameworkConfigGrid")]
    public partial class FrameworkConfigGrid : Row
    {
        [SqlColumn("Id", typeof(FrameworkConfigGrid_Id), true)]
        public int Id { get; set; }

        [SqlColumn("GridId", typeof(FrameworkConfigGrid_GridId))]
        public int GridId { get; set; }

        [SqlColumn("PageRowCountDefault", typeof(FrameworkConfigGrid_PageRowCountDefault))]
        public int? PageRowCountDefault { get; set; }

        [SqlColumn("PageRowCount", typeof(FrameworkConfigGrid_PageRowCount))]
        public int? PageRowCount { get; set; }

        [SqlColumn("PageColumnCountDefault", typeof(FrameworkConfigGrid_PageColumnCountDefault))]
        public int? PageColumnCountDefault { get; set; }

        [SqlColumn("PageColumnCount", typeof(FrameworkConfigGrid_PageColumnCount))]
        public int? PageColumnCount { get; set; }

        [SqlColumn("IsInsertDefault", typeof(FrameworkConfigGrid_IsInsertDefault))]
        public bool? IsInsertDefault { get; set; }

        [SqlColumn("IsInsert", typeof(FrameworkConfigGrid_IsInsert))]
        public bool? IsInsert { get; set; }
    }

    public partial class FrameworkConfigGrid_Id : Cell<FrameworkConfigGrid> { }

    public partial class FrameworkConfigGrid_GridId : Cell<FrameworkConfigGrid> { }

    public partial class FrameworkConfigGrid_PageRowCountDefault : Cell<FrameworkConfigGrid> { }

    public partial class FrameworkConfigGrid_PageRowCount : Cell<FrameworkConfigGrid> { }

    public partial class FrameworkConfigGrid_PageColumnCountDefault : Cell<FrameworkConfigGrid> { }

    public partial class FrameworkConfigGrid_PageColumnCount : Cell<FrameworkConfigGrid> { }

    public partial class FrameworkConfigGrid_IsInsertDefault : Cell<FrameworkConfigGrid> { }

    public partial class FrameworkConfigGrid_IsInsert : Cell<FrameworkConfigGrid> { }

    [SqlTable("dbo", "FrameworkConfigGridDisplay")]
    public partial class FrameworkConfigGridDisplay : Row
    {
        [SqlColumn("GridId", typeof(FrameworkConfigGridDisplay_GridId))]
        public int GridId { get; set; }

        [SqlColumn("GridName", typeof(FrameworkConfigGridDisplay_GridName))]
        public string GridName { get; set; }

        [SqlColumn("GridIsExist", typeof(FrameworkConfigGridDisplay_GridIsExist))]
        public bool GridIsExist { get; set; }

        [SqlColumn("TableId", typeof(FrameworkConfigGridDisplay_TableId))]
        public int? TableId { get; set; }

        [SqlColumn("TableNameCSharp", typeof(FrameworkConfigGridDisplay_TableNameCSharp))]
        public string TableNameCSharp { get; set; }

        [SqlColumn("TableNameSql", typeof(FrameworkConfigGridDisplay_TableNameSql))]
        public string TableNameSql { get; set; }

        [SqlColumn("TableIsExist", typeof(FrameworkConfigGridDisplay_TableIsExist))]
        public bool? TableIsExist { get; set; }

        [SqlColumn("ConfigId", typeof(FrameworkConfigGridDisplay_ConfigId))]
        public int? ConfigId { get; set; }

        [SqlColumn("PageRowCountDefault", typeof(FrameworkConfigGridDisplay_PageRowCountDefault))]
        public int? PageRowCountDefault { get; set; }

        [SqlColumn("PageRowCount", typeof(FrameworkConfigGridDisplay_PageRowCount))]
        public int? PageRowCount { get; set; }

        [SqlColumn("PageColumnCountDefault", typeof(FrameworkConfigGridDisplay_PageColumnCountDefault))]
        public int? PageColumnCountDefault { get; set; }

        [SqlColumn("PageColumnCount", typeof(FrameworkConfigGridDisplay_PageColumnCount))]
        public int? PageColumnCount { get; set; }

        [SqlColumn("IsInsertDefault", typeof(FrameworkConfigGridDisplay_IsInsertDefault))]
        public bool? IsInsertDefault { get; set; }

        [SqlColumn("IsInsert", typeof(FrameworkConfigGridDisplay_IsInsert))]
        public bool? IsInsert { get; set; }
    }

    public partial class FrameworkConfigGridDisplay_GridId : Cell<FrameworkConfigGridDisplay> { }

    public partial class FrameworkConfigGridDisplay_GridName : Cell<FrameworkConfigGridDisplay> { }

    public partial class FrameworkConfigGridDisplay_GridIsExist : Cell<FrameworkConfigGridDisplay> { }

    public partial class FrameworkConfigGridDisplay_TableId : Cell<FrameworkConfigGridDisplay> { }

    public partial class FrameworkConfigGridDisplay_TableNameCSharp : Cell<FrameworkConfigGridDisplay> { }

    public partial class FrameworkConfigGridDisplay_TableNameSql : Cell<FrameworkConfigGridDisplay> { }

    public partial class FrameworkConfigGridDisplay_TableIsExist : Cell<FrameworkConfigGridDisplay> { }

    public partial class FrameworkConfigGridDisplay_ConfigId : Cell<FrameworkConfigGridDisplay> { }

    public partial class FrameworkConfigGridDisplay_PageRowCountDefault : Cell<FrameworkConfigGridDisplay> { }

    public partial class FrameworkConfigGridDisplay_PageRowCount : Cell<FrameworkConfigGridDisplay> { }

    public partial class FrameworkConfigGridDisplay_PageColumnCountDefault : Cell<FrameworkConfigGridDisplay> { }

    public partial class FrameworkConfigGridDisplay_PageColumnCount : Cell<FrameworkConfigGridDisplay> { }

    public partial class FrameworkConfigGridDisplay_IsInsertDefault : Cell<FrameworkConfigGridDisplay> { }

    public partial class FrameworkConfigGridDisplay_IsInsert : Cell<FrameworkConfigGridDisplay> { }

    [SqlTable("dbo", "FrameworkFileStorage")]
    public partial class FrameworkFileStorage : Row
    {
        [SqlColumn("Id", typeof(FrameworkFileStorage_Id), true)]
        public int Id { get; set; }

        [SqlColumn("ApplicationId", typeof(FrameworkFileStorage_ApplicationId))]
        public int? ApplicationId { get; set; }

        [SqlColumn("Name", typeof(FrameworkFileStorage_Name))]
        public string Name { get; set; }

        [SqlColumn("FileNameUpload", typeof(FrameworkFileStorage_FileNameUpload))]
        public string FileNameUpload { get; set; }

        [SqlColumn("Data", typeof(FrameworkFileStorage_Data))]
        public byte[] Data { get; set; }

        [SqlColumn("IsDelete", typeof(FrameworkFileStorage_IsDelete))]
        public bool? IsDelete { get; set; }
    }

    public partial class FrameworkFileStorage_Id : Cell<FrameworkFileStorage> { }

    public partial class FrameworkFileStorage_ApplicationId : Cell<FrameworkFileStorage> { }

    public partial class FrameworkFileStorage_Name : Cell<FrameworkFileStorage> { }

    public partial class FrameworkFileStorage_FileNameUpload : Cell<FrameworkFileStorage> { }

    public partial class FrameworkFileStorage_Data : Cell<FrameworkFileStorage> { }

    public partial class FrameworkFileStorage_IsDelete : Cell<FrameworkFileStorage> { }

    [SqlTable("dbo", "FrameworkGrid")]
    public partial class FrameworkGrid : Row
    {
        [SqlColumn("Id", typeof(FrameworkGrid_Id), true)]
        public int Id { get; set; }

        [SqlColumn("TableId", typeof(FrameworkGrid_TableId))]
        public int TableId { get; set; }

        [SqlColumn("GridName", typeof(FrameworkGrid_GridName))]
        public string GridName { get; set; }

        [SqlColumn("IsExist", typeof(FrameworkGrid_IsExist))]
        public bool IsExist { get; set; }
    }

    public partial class FrameworkGrid_Id : Cell<FrameworkGrid> { }

    public partial class FrameworkGrid_TableId : Cell<FrameworkGrid> { }

    public partial class FrameworkGrid_GridName : Cell<FrameworkGrid> { }

    public partial class FrameworkGrid_IsExist : Cell<FrameworkGrid> { }

    [SqlTable("dbo", "FrameworkLoginPermission")]
    public partial class FrameworkLoginPermission : Row
    {
        [SqlColumn("Id", typeof(FrameworkLoginPermission_Id), true)]
        public int Id { get; set; }

        [SqlColumn("ApplicationTypeId", typeof(FrameworkLoginPermission_ApplicationTypeId))]
        public int ApplicationTypeId { get; set; }

        [SqlColumn("PermissionName", typeof(FrameworkLoginPermission_PermissionName))]
        public string PermissionName { get; set; }

        [SqlColumn("Description", typeof(FrameworkLoginPermission_Description))]
        public string Description { get; set; }

        [SqlColumn("IsExist", typeof(FrameworkLoginPermission_IsExist))]
        public bool IsExist { get; set; }
    }

    public partial class FrameworkLoginPermission_Id : Cell<FrameworkLoginPermission> { }

    public partial class FrameworkLoginPermission_ApplicationTypeId : Cell<FrameworkLoginPermission> { }

    public partial class FrameworkLoginPermission_PermissionName : Cell<FrameworkLoginPermission> { }

    public partial class FrameworkLoginPermission_Description : Cell<FrameworkLoginPermission> { }

    public partial class FrameworkLoginPermission_IsExist : Cell<FrameworkLoginPermission> { }

    [SqlTable("dbo", "FrameworkLoginPermissionDisplay")]
    public partial class FrameworkLoginPermissionDisplay : Row
    {
        [SqlColumn("Id", typeof(FrameworkLoginPermissionDisplay_Id))]
        public int Id { get; set; }

        [SqlColumn("ApplicationTypeId", typeof(FrameworkLoginPermissionDisplay_ApplicationTypeId))]
        public int ApplicationTypeId { get; set; }

        [SqlColumn("ApplicationTypeName", typeof(FrameworkLoginPermissionDisplay_ApplicationTypeName))]
        public string ApplicationTypeName { get; set; }

        [SqlColumn("PermissionName", typeof(FrameworkLoginPermissionDisplay_PermissionName))]
        public string PermissionName { get; set; }

        [SqlColumn("Description", typeof(FrameworkLoginPermissionDisplay_Description))]
        public string Description { get; set; }

        [SqlColumn("IsExist", typeof(FrameworkLoginPermissionDisplay_IsExist))]
        public bool IsExist { get; set; }
    }

    public partial class FrameworkLoginPermissionDisplay_Id : Cell<FrameworkLoginPermissionDisplay> { }

    public partial class FrameworkLoginPermissionDisplay_ApplicationTypeId : Cell<FrameworkLoginPermissionDisplay> { }

    public partial class FrameworkLoginPermissionDisplay_ApplicationTypeName : Cell<FrameworkLoginPermissionDisplay> { }

    public partial class FrameworkLoginPermissionDisplay_PermissionName : Cell<FrameworkLoginPermissionDisplay> { }

    public partial class FrameworkLoginPermissionDisplay_Description : Cell<FrameworkLoginPermissionDisplay> { }

    public partial class FrameworkLoginPermissionDisplay_IsExist : Cell<FrameworkLoginPermissionDisplay> { }

    [SqlTable("dbo", "FrameworkLoginRole")]
    public partial class FrameworkLoginRole : Row
    {
        [SqlColumn("Id", typeof(FrameworkLoginRole_Id), true)]
        public int Id { get; set; }

        [SqlColumn("ApplicationId", typeof(FrameworkLoginRole_ApplicationId))]
        public int? ApplicationId { get; set; }

        [SqlColumn("ApplicationTypeId", typeof(FrameworkLoginRole_ApplicationTypeId))]
        public int? ApplicationTypeId { get; set; }

        [SqlColumn("RoleName", typeof(FrameworkLoginRole_RoleName))]
        public string RoleName { get; set; }

        [SqlColumn("Description", typeof(FrameworkLoginRole_Description))]
        public string Description { get; set; }

        [SqlColumn("IsBuiltIn", typeof(FrameworkLoginRole_IsBuiltIn))]
        public bool IsBuiltIn { get; set; }

        [SqlColumn("IsBuiltInExist", typeof(FrameworkLoginRole_IsBuiltInExist))]
        public bool IsBuiltInExist { get; set; }
    }

    public partial class FrameworkLoginRole_Id : Cell<FrameworkLoginRole> { }

    public partial class FrameworkLoginRole_ApplicationId : Cell<FrameworkLoginRole> { }

    public partial class FrameworkLoginRole_ApplicationTypeId : Cell<FrameworkLoginRole> { }

    public partial class FrameworkLoginRole_RoleName : Cell<FrameworkLoginRole> { }

    public partial class FrameworkLoginRole_Description : Cell<FrameworkLoginRole> { }

    public partial class FrameworkLoginRole_IsBuiltIn : Cell<FrameworkLoginRole> { }

    public partial class FrameworkLoginRole_IsBuiltInExist : Cell<FrameworkLoginRole> { }

    [SqlTable("dbo", "FrameworkLoginRoleDisplay")]
    public partial class FrameworkLoginRoleDisplay : Row
    {
        [SqlColumn("Id", typeof(FrameworkLoginRoleDisplay_Id))]
        public int Id { get; set; }

        [SqlColumn("ApplicationId", typeof(FrameworkLoginRoleDisplay_ApplicationId))]
        public int? ApplicationId { get; set; }

        [SqlColumn("ApplicationTypeId", typeof(FrameworkLoginRoleDisplay_ApplicationTypeId))]
        public int? ApplicationTypeId { get; set; }

        [SqlColumn("ApplicationTypeName", typeof(FrameworkLoginRoleDisplay_ApplicationTypeName))]
        public string ApplicationTypeName { get; set; }

        [SqlColumn("RoleName", typeof(FrameworkLoginRoleDisplay_RoleName))]
        public string RoleName { get; set; }

        [SqlColumn("Description", typeof(FrameworkLoginRoleDisplay_Description))]
        public string Description { get; set; }

        [SqlColumn("IsBuiltIn", typeof(FrameworkLoginRoleDisplay_IsBuiltIn))]
        public bool IsBuiltIn { get; set; }

        [SqlColumn("IsBuiltInExist", typeof(FrameworkLoginRoleDisplay_IsBuiltInExist))]
        public bool IsBuiltInExist { get; set; }
    }

    public partial class FrameworkLoginRoleDisplay_Id : Cell<FrameworkLoginRoleDisplay> { }

    public partial class FrameworkLoginRoleDisplay_ApplicationId : Cell<FrameworkLoginRoleDisplay> { }

    public partial class FrameworkLoginRoleDisplay_ApplicationTypeId : Cell<FrameworkLoginRoleDisplay> { }

    public partial class FrameworkLoginRoleDisplay_ApplicationTypeName : Cell<FrameworkLoginRoleDisplay> { }

    public partial class FrameworkLoginRoleDisplay_RoleName : Cell<FrameworkLoginRoleDisplay> { }

    public partial class FrameworkLoginRoleDisplay_Description : Cell<FrameworkLoginRoleDisplay> { }

    public partial class FrameworkLoginRoleDisplay_IsBuiltIn : Cell<FrameworkLoginRoleDisplay> { }

    public partial class FrameworkLoginRoleDisplay_IsBuiltInExist : Cell<FrameworkLoginRoleDisplay> { }

    [SqlTable("dbo", "FrameworkLoginRolePermission")]
    public partial class FrameworkLoginRolePermission : Row
    {
        [SqlColumn("Id", typeof(FrameworkLoginRolePermission_Id), true)]
        public int Id { get; set; }

        [SqlColumn("RoleId", typeof(FrameworkLoginRolePermission_RoleId))]
        public int RoleId { get; set; }

        [SqlColumn("PermissionId", typeof(FrameworkLoginRolePermission_PermissionId))]
        public int PermissionId { get; set; }

        [SqlColumn("IsBuiltIn", typeof(FrameworkLoginRolePermission_IsBuiltIn))]
        public bool IsBuiltIn { get; set; }

        [SqlColumn("IsActive", typeof(FrameworkLoginRolePermission_IsActive))]
        public bool IsActive { get; set; }
    }

    public partial class FrameworkLoginRolePermission_Id : Cell<FrameworkLoginRolePermission> { }

    public partial class FrameworkLoginRolePermission_RoleId : Cell<FrameworkLoginRolePermission> { }

    public partial class FrameworkLoginRolePermission_PermissionId : Cell<FrameworkLoginRolePermission> { }

    public partial class FrameworkLoginRolePermission_IsBuiltIn : Cell<FrameworkLoginRolePermission> { }

    public partial class FrameworkLoginRolePermission_IsActive : Cell<FrameworkLoginRolePermission> { }

    [SqlTable("dbo", "FrameworkLoginRolePermissionDisplay")]
    public partial class FrameworkLoginRolePermissionDisplay : Row
    {
        [SqlColumn("Id", typeof(FrameworkLoginRolePermissionDisplay_Id))]
        public int Id { get; set; }

        [SqlColumn("RoleId", typeof(FrameworkLoginRolePermissionDisplay_RoleId))]
        public int RoleId { get; set; }

        [SqlColumn("PermissionId", typeof(FrameworkLoginRolePermissionDisplay_PermissionId))]
        public int PermissionId { get; set; }

        [SqlColumn("IsBuiltIn", typeof(FrameworkLoginRolePermissionDisplay_IsBuiltIn))]
        public bool IsBuiltIn { get; set; }

        [SqlColumn("IsActive", typeof(FrameworkLoginRolePermissionDisplay_IsActive))]
        public bool IsActive { get; set; }

        [SqlColumn("RoleRoleId", typeof(FrameworkLoginRolePermissionDisplay_RoleRoleId))]
        public int? RoleRoleId { get; set; }

        [SqlColumn("RoleRoleName", typeof(FrameworkLoginRolePermissionDisplay_RoleRoleName))]
        public string RoleRoleName { get; set; }

        [SqlColumn("RoleIsBuiltIn", typeof(FrameworkLoginRolePermissionDisplay_RoleIsBuiltIn))]
        public bool? RoleIsBuiltIn { get; set; }

        [SqlColumn("RoleIsBuiltInExist", typeof(FrameworkLoginRolePermissionDisplay_RoleIsBuiltInExist))]
        public bool? RoleIsBuiltInExist { get; set; }

        [SqlColumn("PermissionPermissionId", typeof(FrameworkLoginRolePermissionDisplay_PermissionPermissionId))]
        public int? PermissionPermissionId { get; set; }

        [SqlColumn("PermissionPermissionName", typeof(FrameworkLoginRolePermissionDisplay_PermissionPermissionName))]
        public string PermissionPermissionName { get; set; }

        [SqlColumn("PermissionIsExist", typeof(FrameworkLoginRolePermissionDisplay_PermissionIsExist))]
        public bool? PermissionIsExist { get; set; }

        [SqlColumn("ApplicationTypeId", typeof(FrameworkLoginRolePermissionDisplay_ApplicationTypeId))]
        public int? ApplicationTypeId { get; set; }

        [SqlColumn("ApplicationTypeTypeName", typeof(FrameworkLoginRolePermissionDisplay_ApplicationTypeTypeName))]
        public string ApplicationTypeTypeName { get; set; }
    }

    public partial class FrameworkLoginRolePermissionDisplay_Id : Cell<FrameworkLoginRolePermissionDisplay> { }

    public partial class FrameworkLoginRolePermissionDisplay_RoleId : Cell<FrameworkLoginRolePermissionDisplay> { }

    public partial class FrameworkLoginRolePermissionDisplay_PermissionId : Cell<FrameworkLoginRolePermissionDisplay> { }

    public partial class FrameworkLoginRolePermissionDisplay_IsBuiltIn : Cell<FrameworkLoginRolePermissionDisplay> { }

    public partial class FrameworkLoginRolePermissionDisplay_IsActive : Cell<FrameworkLoginRolePermissionDisplay> { }

    public partial class FrameworkLoginRolePermissionDisplay_RoleRoleId : Cell<FrameworkLoginRolePermissionDisplay> { }

    public partial class FrameworkLoginRolePermissionDisplay_RoleRoleName : Cell<FrameworkLoginRolePermissionDisplay> { }

    public partial class FrameworkLoginRolePermissionDisplay_RoleIsBuiltIn : Cell<FrameworkLoginRolePermissionDisplay> { }

    public partial class FrameworkLoginRolePermissionDisplay_RoleIsBuiltInExist : Cell<FrameworkLoginRolePermissionDisplay> { }

    public partial class FrameworkLoginRolePermissionDisplay_PermissionPermissionId : Cell<FrameworkLoginRolePermissionDisplay> { }

    public partial class FrameworkLoginRolePermissionDisplay_PermissionPermissionName : Cell<FrameworkLoginRolePermissionDisplay> { }

    public partial class FrameworkLoginRolePermissionDisplay_PermissionIsExist : Cell<FrameworkLoginRolePermissionDisplay> { }

    public partial class FrameworkLoginRolePermissionDisplay_ApplicationTypeId : Cell<FrameworkLoginRolePermissionDisplay> { }

    public partial class FrameworkLoginRolePermissionDisplay_ApplicationTypeTypeName : Cell<FrameworkLoginRolePermissionDisplay> { }

    [SqlTable("dbo", "FrameworkLoginUser")]
    public partial class FrameworkLoginUser : Row
    {
        [SqlColumn("Id", typeof(FrameworkLoginUser_Id), true)]
        public int Id { get; set; }

        [SqlColumn("ApplicationId", typeof(FrameworkLoginUser_ApplicationId))]
        public int? ApplicationId { get; set; }

        [SqlColumn("ApplicationTypeId", typeof(FrameworkLoginUser_ApplicationTypeId))]
        public int? ApplicationTypeId { get; set; }

        [SqlColumn("UserName", typeof(FrameworkLoginUser_UserName))]
        public string UserName { get; set; }

        [SqlColumn("Password", typeof(FrameworkLoginUser_Password))]
        public string Password { get; set; }

        [SqlColumn("IsBuiltIn", typeof(FrameworkLoginUser_IsBuiltIn))]
        public bool IsBuiltIn { get; set; }

        [SqlColumn("IsBuiltInExist", typeof(FrameworkLoginUser_IsBuiltInExist))]
        public bool IsBuiltInExist { get; set; }
    }

    public partial class FrameworkLoginUser_Id : Cell<FrameworkLoginUser> { }

    public partial class FrameworkLoginUser_ApplicationId : Cell<FrameworkLoginUser> { }

    public partial class FrameworkLoginUser_ApplicationTypeId : Cell<FrameworkLoginUser> { }

    public partial class FrameworkLoginUser_UserName : Cell<FrameworkLoginUser> { }

    public partial class FrameworkLoginUser_Password : Cell<FrameworkLoginUser> { }

    public partial class FrameworkLoginUser_IsBuiltIn : Cell<FrameworkLoginUser> { }

    public partial class FrameworkLoginUser_IsBuiltInExist : Cell<FrameworkLoginUser> { }

    [SqlTable("dbo", "FrameworkLoginUserDisplay")]
    public partial class FrameworkLoginUserDisplay : Row
    {
        [SqlColumn("Id", typeof(FrameworkLoginUserDisplay_Id))]
        public int Id { get; set; }

        [SqlColumn("ApplicationId", typeof(FrameworkLoginUserDisplay_ApplicationId))]
        public int? ApplicationId { get; set; }

        [SqlColumn("ApplicationText", typeof(FrameworkLoginUserDisplay_ApplicationText))]
        public string ApplicationText { get; set; }

        [SqlColumn("ApplicationTypeId", typeof(FrameworkLoginUserDisplay_ApplicationTypeId))]
        public int? ApplicationTypeId { get; set; }

        [SqlColumn("ApplicationTypeName", typeof(FrameworkLoginUserDisplay_ApplicationTypeName))]
        public string ApplicationTypeName { get; set; }

        [SqlColumn("UserName", typeof(FrameworkLoginUserDisplay_UserName))]
        public string UserName { get; set; }

        [SqlColumn("Password", typeof(FrameworkLoginUserDisplay_Password))]
        public string Password { get; set; }

        [SqlColumn("IsBuiltIn", typeof(FrameworkLoginUserDisplay_IsBuiltIn))]
        public bool IsBuiltIn { get; set; }

        [SqlColumn("IsBuiltInExist", typeof(FrameworkLoginUserDisplay_IsBuiltInExist))]
        public bool IsBuiltInExist { get; set; }
    }

    public partial class FrameworkLoginUserDisplay_Id : Cell<FrameworkLoginUserDisplay> { }

    public partial class FrameworkLoginUserDisplay_ApplicationId : Cell<FrameworkLoginUserDisplay> { }

    public partial class FrameworkLoginUserDisplay_ApplicationText : Cell<FrameworkLoginUserDisplay> { }

    public partial class FrameworkLoginUserDisplay_ApplicationTypeId : Cell<FrameworkLoginUserDisplay> { }

    public partial class FrameworkLoginUserDisplay_ApplicationTypeName : Cell<FrameworkLoginUserDisplay> { }

    public partial class FrameworkLoginUserDisplay_UserName : Cell<FrameworkLoginUserDisplay> { }

    public partial class FrameworkLoginUserDisplay_Password : Cell<FrameworkLoginUserDisplay> { }

    public partial class FrameworkLoginUserDisplay_IsBuiltIn : Cell<FrameworkLoginUserDisplay> { }

    public partial class FrameworkLoginUserDisplay_IsBuiltInExist : Cell<FrameworkLoginUserDisplay> { }

    [SqlTable("dbo", "FrameworkLoginUserRole")]
    public partial class FrameworkLoginUserRole : Row
    {
        [SqlColumn("Id", typeof(FrameworkLoginUserRole_Id), true)]
        public int Id { get; set; }

        [SqlColumn("UserId", typeof(FrameworkLoginUserRole_UserId))]
        public int UserId { get; set; }

        [SqlColumn("RoleId", typeof(FrameworkLoginUserRole_RoleId))]
        public int RoleId { get; set; }

        [SqlColumn("IsBuiltIn", typeof(FrameworkLoginUserRole_IsBuiltIn))]
        public bool IsBuiltIn { get; set; }

        [SqlColumn("IsActive", typeof(FrameworkLoginUserRole_IsActive))]
        public bool IsActive { get; set; }
    }

    public partial class FrameworkLoginUserRole_Id : Cell<FrameworkLoginUserRole> { }

    public partial class FrameworkLoginUserRole_UserId : Cell<FrameworkLoginUserRole> { }

    public partial class FrameworkLoginUserRole_RoleId : Cell<FrameworkLoginUserRole> { }

    public partial class FrameworkLoginUserRole_IsBuiltIn : Cell<FrameworkLoginUserRole> { }

    public partial class FrameworkLoginUserRole_IsActive : Cell<FrameworkLoginUserRole> { }

    [SqlTable("dbo", "FrameworkLoginUserRoleDisplay")]
    public partial class FrameworkLoginUserRoleDisplay : Row
    {
        [SqlColumn("UserId", typeof(FrameworkLoginUserRoleDisplay_UserId))]
        public int UserId { get; set; }

        [SqlColumn("UserApplicationId", typeof(FrameworkLoginUserRoleDisplay_UserApplicationId))]
        public int? UserApplicationId { get; set; }

        [SqlColumn("UserUserName", typeof(FrameworkLoginUserRoleDisplay_UserUserName))]
        public string UserUserName { get; set; }

        [SqlColumn("UserPassword", typeof(FrameworkLoginUserRoleDisplay_UserPassword))]
        public string UserPassword { get; set; }

        [SqlColumn("UserIsBuiltIn", typeof(FrameworkLoginUserRoleDisplay_UserIsBuiltIn))]
        public bool UserIsBuiltIn { get; set; }

        [SqlColumn("RoleId", typeof(FrameworkLoginUserRoleDisplay_RoleId))]
        public int? RoleId { get; set; }

        [SqlColumn("RoleRoleName", typeof(FrameworkLoginUserRoleDisplay_RoleRoleName))]
        public string RoleRoleName { get; set; }

        [SqlColumn("RoleDescription", typeof(FrameworkLoginUserRoleDisplay_RoleDescription))]
        public string RoleDescription { get; set; }

        [SqlColumn("RoleIsBuiltIn", typeof(FrameworkLoginUserRoleDisplay_RoleIsBuiltIn))]
        public bool? RoleIsBuiltIn { get; set; }

        [SqlColumn("UserRoleId", typeof(FrameworkLoginUserRoleDisplay_UserRoleId))]
        public int? UserRoleId { get; set; }

        [SqlColumn("UserRoleIsActive", typeof(FrameworkLoginUserRoleDisplay_UserRoleIsActive))]
        public bool? UserRoleIsActive { get; set; }
    }

    public partial class FrameworkLoginUserRoleDisplay_UserId : Cell<FrameworkLoginUserRoleDisplay> { }

    public partial class FrameworkLoginUserRoleDisplay_UserApplicationId : Cell<FrameworkLoginUserRoleDisplay> { }

    public partial class FrameworkLoginUserRoleDisplay_UserUserName : Cell<FrameworkLoginUserRoleDisplay> { }

    public partial class FrameworkLoginUserRoleDisplay_UserPassword : Cell<FrameworkLoginUserRoleDisplay> { }

    public partial class FrameworkLoginUserRoleDisplay_UserIsBuiltIn : Cell<FrameworkLoginUserRoleDisplay> { }

    public partial class FrameworkLoginUserRoleDisplay_RoleId : Cell<FrameworkLoginUserRoleDisplay> { }

    public partial class FrameworkLoginUserRoleDisplay_RoleRoleName : Cell<FrameworkLoginUserRoleDisplay> { }

    public partial class FrameworkLoginUserRoleDisplay_RoleDescription : Cell<FrameworkLoginUserRoleDisplay> { }

    public partial class FrameworkLoginUserRoleDisplay_RoleIsBuiltIn : Cell<FrameworkLoginUserRoleDisplay> { }

    public partial class FrameworkLoginUserRoleDisplay_UserRoleId : Cell<FrameworkLoginUserRoleDisplay> { }

    public partial class FrameworkLoginUserRoleDisplay_UserRoleIsActive : Cell<FrameworkLoginUserRoleDisplay> { }

    [SqlTable("dbo", "FrameworkNavigation")]
    public partial class FrameworkNavigation : Row
    {
        [SqlColumn("Id", typeof(FrameworkNavigation_Id), true)]
        public int Id { get; set; }

        [SqlColumn("Text", typeof(FrameworkNavigation_Text))]
        public string Text { get; set; }

        [SqlColumn("ComponentId", typeof(FrameworkNavigation_ComponentId))]
        public int? ComponentId { get; set; }
    }

    public partial class FrameworkNavigation_Id : Cell<FrameworkNavigation> { }

    public partial class FrameworkNavigation_Text : Cell<FrameworkNavigation> { }

    public partial class FrameworkNavigation_ComponentId : Cell<FrameworkNavigation> { }

    [SqlTable("dbo", "FrameworkNavigationDisplay")]
    public partial class FrameworkNavigationDisplay : Row
    {
        [SqlColumn("Id", typeof(FrameworkNavigationDisplay_Id))]
        public int Id { get; set; }

        [SqlColumn("Text", typeof(FrameworkNavigationDisplay_Text))]
        public string Text { get; set; }

        [SqlColumn("ComponentId", typeof(FrameworkNavigationDisplay_ComponentId))]
        public int? ComponentId { get; set; }

        [SqlColumn("ComponentNameCSharp", typeof(FrameworkNavigationDisplay_ComponentNameCSharp))]
        public string ComponentNameCSharp { get; set; }
    }

    public partial class FrameworkNavigationDisplay_Id : Cell<FrameworkNavigationDisplay> { }

    public partial class FrameworkNavigationDisplay_Text : Cell<FrameworkNavigationDisplay> { }

    public partial class FrameworkNavigationDisplay_ComponentId : Cell<FrameworkNavigationDisplay> { }

    public partial class FrameworkNavigationDisplay_ComponentNameCSharp : Cell<FrameworkNavigationDisplay> { }

    [SqlTable("dbo", "FrameworkScript")]
    public partial class FrameworkScript : Row
    {
        [SqlColumn("Id", typeof(FrameworkScript_Id), true)]
        public int Id { get; set; }

        [SqlColumn("Name", typeof(FrameworkScript_Name))]
        public string Name { get; set; }

        [SqlColumn("IsExist", typeof(FrameworkScript_IsExist))]
        public bool IsExist { get; set; }

        [SqlColumn("IsRun", typeof(FrameworkScript_IsRun))]
        public bool IsRun { get; set; }

        [SqlColumn("DateCreate", typeof(FrameworkScript_DateCreate))]
        public DateTime? DateCreate { get; set; }

        [SqlColumn("DateDrop", typeof(FrameworkScript_DateDrop))]
        public DateTime? DateDrop { get; set; }
    }

    public partial class FrameworkScript_Id : Cell<FrameworkScript> { }

    public partial class FrameworkScript_Name : Cell<FrameworkScript> { }

    public partial class FrameworkScript_IsExist : Cell<FrameworkScript> { }

    public partial class FrameworkScript_IsRun : Cell<FrameworkScript> { }

    public partial class FrameworkScript_DateCreate : Cell<FrameworkScript> { }

    public partial class FrameworkScript_DateDrop : Cell<FrameworkScript> { }

    [SqlTable("dbo", "FrameworkSession")]
    public partial class FrameworkSession : Row
    {
        [SqlColumn("Id", typeof(FrameworkSession_Id), true)]
        public int Id { get; set; }

        [SqlColumn("Session", typeof(FrameworkSession_Session))]
        public Guid Session { get; set; }

        [SqlColumn("ApplicationId", typeof(FrameworkSession_ApplicationId))]
        public int ApplicationId { get; set; }

        [SqlColumn("UserId", typeof(FrameworkSession_UserId))]
        public int UserId { get; set; }
    }

    public partial class FrameworkSession_Id : Cell<FrameworkSession> { }

    public partial class FrameworkSession_Session : Cell<FrameworkSession> { }

    public partial class FrameworkSession_ApplicationId : Cell<FrameworkSession> { }

    public partial class FrameworkSession_UserId : Cell<FrameworkSession> { }

    [SqlTable("dbo", "FrameworkTable")]
    public partial class FrameworkTable : Row
    {
        [SqlColumn("Id", typeof(FrameworkTable_Id), true)]
        public int Id { get; set; }

        [SqlColumn("TableNameCSharp", typeof(FrameworkTable_TableNameCSharp))]
        public string TableNameCSharp { get; set; }

        [SqlColumn("TableNameSql", typeof(FrameworkTable_TableNameSql))]
        public string TableNameSql { get; set; }

        [SqlColumn("IsExist", typeof(FrameworkTable_IsExist))]
        public bool IsExist { get; set; }
    }

    public partial class FrameworkTable_Id : Cell<FrameworkTable> { }

    public partial class FrameworkTable_TableNameCSharp : Cell<FrameworkTable> { }

    public partial class FrameworkTable_TableNameSql : Cell<FrameworkTable> { }

    public partial class FrameworkTable_IsExist : Cell<FrameworkTable> { }
}
