# Copy this file from "./Framework/Framework.Cli/Ci/github.com/.main.yml" to "./.github/workflows/main.yml"

name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install script
      env: 
        My: ${{ secrets.My }} 
      run: ./Framework/Framework.Cli/Ci/github.com/Install.sh
    - name: Build script
      run: ./Framework/Framework.Cli/Ci/github.com/build.sh
