# Copy this file from "./Framework/Framework.Cli/Ci/github.com/.main.yml" to "./.github/workflows/main.yml"

name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install script
      env: 
        ConfigCli: ${{ secrets.ConfigCli }} 
      run: ./Framework/Framework.Cli/Ci/github.com/install.sh
    - name: Build script
      run: ./Framework/Framework.Cli/Ci/github.com/build.sh
