// Do not modify this file. It's generated by Framework.Cli generate command.

namespace DatabaseIntegrate.dbo
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Database.dbo;

    public static class FrameworkConfigGridIntegrateAppCli
    {
        public static List<FrameworkConfigGridIntegrate> RowList
        {
            get
            {
                var result = new List<FrameworkConfigGridIntegrate>
                {
                };
                return result;
            }
        }
    }

    public static class FrameworkConfigFieldIntegrateAppCli
    {
        public static List<FrameworkConfigFieldIntegrate> RowList
        {
            get
            {
                var result = new List<FrameworkConfigFieldIntegrate>
                {
                };
                return result;
            }
        }
    }

    public static class HelloWorldIntegrateAppCli
    {
        public static List<HelloWorldIntegrate> RowList
        {
            get
            {
                var result = new List<HelloWorldIntegrate>
                {
                    new HelloWorldIntegrate { Id = 0, Name = "One", Text = "Hello", Number = 1, IdName = "One" },
                    new HelloWorldIntegrate { Id = 0, Name = "Two", Text = "World", Number = 2, IdName = "Two" },
                };
                return result;
            }
        }
    }
}
